---
name: Spear Docker Exec Runner
description: A GitHub action to run actions inside of the project's docker container
branding:
  icon: check-circle
  color: green
runs:
  using: composite
  steps:

    - if: inputs.command && inputs.entrypointFile
      run: echo "SPECIFY ONLY command OR entrypointFile" && false
      shell: bash

    - run: test -f .buildconfig
      shell: bash

    - id: setup
      run: |
        if [[ -n "${{ inputs.command }}" ]]
        then
          echo "${{ inputs.command }}" > ${GITHUB_WORKSPACE}/action-entrypoint.sh
          chmod +x ${GITHUB_WORKSPACE}/action-entrypoint.sh
          echo "entrypoint=action-entrypoint.sh" >> ${GITHUB_OUTPUT}
        elif [[ -n "${{ inputs.entrypointFile }}" ]]
        then
          echo "entrypoint=${{ inputs.entrypointFile }}" >> ${GITHUB_OUTPUT}
        else
          echo "No command or entrypointFile specified" && false
        fi
      shell: bash

    - id: execute
      run: |
        set -x
        . .buildconfig
        if [[ -n "${{ job.container.id }}" ]]
        then
          VOLUMES="--volumes-from ${{ job.container.id }}"
        else
          VOLUMES="-v $(pwd):${GITHUB_WORKSPACE}:rw"
        fi
        docker run --rm ${VOLUMES} \
          --network '${{ inputs.network }}' \
          -w "${GITHUB_WORKSPACE}" \
          -e SKIP_SECRETS=1 \
          -e SKIP_SERVICES=1 \
          --entrypoint="${{ steps.setup.outputs.entrypoint }}" \
          ${DOCKER_REGISTRY}/${DOCKER_BASE_IMAGE_NAME}:${DOCKER_BASE_IMAGE_VER}
      shell: bash

    - run: rm action-entrypoint.sh || true
      shell: bash

inputs:
  command:
    description: The command to run in the container (if entrypoint is not used)
    required: false
  entrypointFile:
    description: The entrypoint file to run in the container (if command is not used)
    required: false
  network:
    description: The docker network to run in
    required: false
    default: ${{ job.container.network }}