---
name: Spear Docker Exec Runner
description: A GitHub action to run actions inside of the project's docker container
branding:
  icon: check-circle
  color: green
runs:
  using: composite
  steps:

    - if: inputs.command && inputs.entrypointFile
      run: echo "SPECIFY ONLY command OR entrypointFile" && false
      shell: bash

    - run: test -f .buildconfig
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash

    - id: setup
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        if [[ -n "${{ inputs.command }}" ]]
        then
          echo "#!/bin/sh" > action-entrypoint.sh
          echo "${{ inputs.command }}" >> action-entrypoint.sh
          chmod +x action-entrypoint.sh
          echo "entrypoint=action-entrypoint.sh" >> ${GITHUB_OUTPUT}
          echo "ENTRYPOINT: $(pwd)/action-entrypoint.sh"
        elif [[ -n "${{ inputs.entrypointFile }}" ]]
        then
          echo "entrypoint=${{ inputs.entrypointFile }}" >> ${GITHUB_OUTPUT}
        else
          echo "No command or entrypointFile specified" && false
        fi
      shell: bash

    - id: debug
      run: pwd && ls -la
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash

    - id: execute
      working-directory: ${{ inputs.workingDirectory }}
      run: |
        set -x
        . .buildconfig
        WORKING_DIR="$(pwd)"
        VOLUMES="-v ${WORKING_DIR}:${WORKING_DIR}:rw"
        if [[ -n "${{ job.container.id }}" ]]
        then
          VOLUMES="--volumes-from ${{ job.container.id }} ${VOLUMES}"
        fi
        docker run --rm ${VOLUMES} \
          --network '${{ inputs.network }}' \
          -w "${WORKING_DIR}" \
          -e SKIP_SECRETS=1 \
          -e SKIP_SERVICES=1 \
          --entrypoint="${{ steps.setup.outputs.entrypoint }}" \
          "${DOCKER_REGISTRY}/${DOCKER_BASE_IMAGE_NAME}:${DOCKER_BASE_IMAGE_VER}"
      shell: bash

    - run: rm action-entrypoint.sh || true
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash

inputs:
  dockerImage:
    description: The docker image to run the command in. Defaults to reading the .buildconfig 
    required: false
  command:
    description: The command to run in the container (if entrypoint is not used)
    required: false
  entrypointFile:
    description: The entrypoint file to run in the container (if command is not used)
    required: false
  network:
    description: The docker network to run in
    required: false
    default: ${{ job.container.network }}
  workingDirectory:
    description: The working directory relative to $GITHUB_WORKSPACE
    required: false
    default: .